<a href="https://colab.research.google.com/github/pankajroy97/BCGX_Gen_AI_Virtual_Job_Internship/blob/main/Task_2_Developing_a_AI_driven_Financial_Chatbot_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
final_report=pd.read_csv('final_data_report.csv')
final_report

,Unnamed: 0,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities,Company,Revenue_growth(%),Net_Income_growth(%),Assets_growth(%),Liabilities_growth(%),cash_flow_growth(%)
0,0,2023,211915,72361,411976,205753,87582,Microsoft,0.000000,0.000000,0.000000,0.000000,0.000000
1,1,2022,198270,72738,364840,198298,89035,Microsoft,-6.438902,0.520999,-11.441443,-3.623276,1.659017
2,2,2021,168088,61271,333779,191791,76740,Microsoft,-15.222676,-15.764800,-8.513595,-3.281425,-13.809176
3,3,2023,96773,14974,106618,43009,13256,Tesla,0.000000,0.000000,0.000000,0.000000,0.000000
4,4,2022,81462,12556,82338,36440,14724,Tesla,-15.821562,-16.147990,-22.772890,-15.273547,11.074231
5,5,2021,53821,5519,62131,30548,11497,Tesla,-33.931158,-56.044919,-24.541524,-16.169045,-21.916599
6,6,2023,383285,96995,352583,290437,110543,Apple,0.000000,0.000000,0.000000,0.000000,0.000000
7,7,2022,394328,99803,352755,302083,122151,Apple,2.881146,2.894995,0.048783,4.009820,10.500891
8,8,2021,365817,94680,351002,287912,104038,Apple,-7.230275,-5.133112,-0.496945,-4.691095,-14.828368

In [ ]:
final_summary=pd.read_csv('/content/summary_csv')

In [ ]:
final_summary

,Company,Revenue_growth(%),Net_Income_growth(%),Assets_growth(%),Liabilities_growth(%),cash_flow_growth(%)
0,Apple,-1.449710,-0.746039,-0.149388,-0.227092,-1.442492
1,Microsoft,-7.220526,-5.081267,-6.651679,-2.301567,-4.050053
2,Tesla,-16.584240,-24.064303,-15.771471,-10.480864,-3.614123

In [ ]:
def final_chatbot():
  print('enter your query:')
  user_query=int(input())


  if user_query==1:
   revenue=final_report[(final_report['Year']==fiscal_year) & (final_report['Company']==company_name)]['Total Revenue'].values[0].round(4)
   return f"The Total Revenue for {company_name} for the year {fiscal_year} is ${revenue}"

  if user_query==2:
   net_income=final_report[(final_report['Year']==fiscal_year) & (final_report['Company']==company_name)]['Net Income'].values[0].round(4)
   return f"The net_income for {company_name} for the year {fiscal_year} is ${net_income}"


  if user_query==3:
   total_assets=final_report[(final_report['Year']==fiscal_year) & (final_report['Company']==company_name)]['Total Assets'].values[0].round(4)
   return f"The Total Assets for {company_name} for the year {fiscal_year} is ${total_assets}"

  if user_query==4:
   total_Liabilities=final_report[(final_report['Year']==fiscal_year) & (final_report['Company']==company_name)]['Total Liabilities'].values[0].round(4)
   return f"The Total Liabilities for {company_name} for the year {fiscal_year} is ${total_Liabilities}"

  if user_query==5:
   Cash_Flow_Activities=final_report[(final_report['Year']==fiscal_year) & (final_report['Company']==company_name)]['Cash Flow from Operating Activities'].values[0].round(4)
   return f"The Cash Flow from Operations for {company_name} for the year {fiscal_year} is ${Cash_Flow_Activities}"

  if user_query==6:
   revenue_growth=final_report[(final_report['Year']==fiscal_year) & (final_report['Company']==company_name)]['Revenue_growth(%)'].values[0].round(4)
   return f"The Total Revenue Growth for {company_name} for the year {fiscal_year} is ${revenue_growth}(%)"


  if user_query==7:
   net_income_growth=final_report[(final_report['Year']==fiscal_year) & (final_report['Company']==company_name)]['Net_Income_growth(%)'].values[0].round(4)
   return f"The Total Net Income Growth for {company_name} for the year {fiscal_year} is ${net_income_growth}(%)"

  if user_query==8:
   assets_growth=final_report[(final_report['Year']==fiscal_year) & (final_report['Company']==company_name)]['Assets_growth(%)'].values[0].round(4)
   return f"The Total Assets Growth for {company_name} for the year {fiscal_year} is ${assets_growth}(%)"

  if user_query==9:
   liabilities_growth=final_report[(final_report['Year']==fiscal_year) & (final_report['Company']==company_name)]['Liabilities_growth(%)'].values[0].round(4)
   return f"The Total Liabilities Growth for {company_name} for the year {fiscal_year} is ${liabilities_growth}(%)"

  if user_query==10:
   year_avg_revenue_growth=final_report[(final_report['Year']==fiscal_year) & (final_report['Company']==company_name)]['cash_flow_growth(%)'].values[0].round(4)
   return f"The Total Cash Flow from Operations Growth for {company_name} for the year {fiscal_year} is ${year_avg_revenue_growth}(%)"

  if user_query==11:
   year_avg_revenue_growth=final_report[final_report['Company']==company_name]['Revenue_growth(%)'].values[0].round(4)
   return f"The Year By Year Average Revenue Growth Rate(%) from 2021 to 2023 for {company_name} is ${year_avg_revenue_growth}(%)"

  if user_query==12:
   year_avg_net_income_growth=final_summary[final_summary['Company']==company_name]['Net_Income_growth(%)'].values[0].round(4)
   return f"The Year By Year Average Net Income Growth Rate(%) from 2021 to 2023 for {company_name} is ${year_avg_net_income_growth}(%)"

  if user_query==13:
   year_avg_assets_growth=final_summary[final_summary['Company']==company_name]['Assets_growth(%)'].values[0].round(4)
   return f"The Year By Year Average Assets Growth Rate(%) from 2021 to 2023 for {company_name} is ${year_avg_assets_growth}(%)"

  if user_query==14:
   year_avg_liabilities_growth=final_summary[final_summary['Company']==company_name]['Liabilities_growth(%)'].values[0].round(4)
   return f"The Year By Year Average Liabilities Growth Rate(%) from 2021 to 2023 for {company_name} is ${year_avg_liabilities_growth}(%)"

  if user_query==15:
   year_avg_cash_ops_growth=final_summary[final_summary['Company']==company_name]['cash_flow_growth(%)'].values[0].round(4)
   return f"The Year By Year Average Cash Flow from Operations Growth Rate(%) from 2021 to 2023 for{company_name} is ${year_avg_cash_ops_growth}(%)"

  else:
   return "Sorry, I cannot only provide information on the requested query."


while True:
 print("-------------------------------------------------------------------------")
 user_input=input("\nEnter Hi to start the chatbot session; type 'exit' to quit):")
 if user_input=="exit":
     break
 elif user_input=="Hi":
       print("\nHello! Welcome to AI Driven Financial Chatbot!!!")
       print("\nI can help you with your financial queries")
       print("Please select the company name from below:")
       print("\n1.Microsoft \n2.Tesla \n3.Apple")
       company_name=input("Enter Company Name: ")
       if company_name not in ["Microsoft","Tesla","Apple"]:
            print("Invalid Company Name. Please check and enter correct company name by starting the chatbot session again")
       else:
            print("The data for the fiscal year 2023, 2022, and 2021 is currently available")
            fiscal_year=int(input("The fiscal year for the selected company :"))
            if fiscal_year not in [2023,2022,2021]:
               print("Please enter a valid fiscal year by starting the chatbot session again")
               break
       print("....FOLLOW THIS INSTRUCTION BEFORE WRITE QUERY....")
       print("****************************************************")
       print("What is the total revenue?----- Write 1")
       print("What is the Net Income?----- Write 2")
       print("What is the sum of total assets?----- Write 3")
       print("What is the sum of total liabilities?----- Write 4")
       print("What is the total Cash Flow from Operating Activitie)?----- Write 5")
       print("What is the revenue growth(%)?----- Write 6")
       print("What is the net income growth(%)?----- Write 7")
       print("What is the assets growth(%)?----- Write 8")
       print("What is the liabilities growth(%)?----- Write 9")
       print("What is the cash flow from operations growth(%)?----- Write 10")
       print("What is the year by year average revenue growth(%)?----- Write 11")
       print("What is the year by year average net income growth rate(%)?----- Write 12")
       print("What is the year by year average assets growth rate(%)?----- Write 13")
       print("What is the year by year average liabilities growth rate(%)?----- Write 14")
       print("What is the year by year average cash flow from operations growth rate(%)?----- Write 15")

 else:
   print("Enter 'Hi' Properly!!!!! by starting the chatbot session again")
   break

 response=final_chatbot()
 print(response)

-------------------------------------------------------------------------

Enter Hi to start the chatbot session; type 'exit' to quit):Hi

Hello! Welcome to AI Driven Financial Chatbot!!!

I can help you with your financial queries
Please select the company name from below:

1.Microsoft
2.Tesla
3.Apple
Enter Company Name: Microsoft
The data for the fiscal year 2023, 2022, and 2021 is currently available
The fiscal year for the selected company :2021
....FOLLOW THIS INSTRUCTION BEFORE WRITE QUERY....
****************************************************
What is the total revenue?----- Write 1
What is the Net Income?----- Write 2
What is the sum of total assets?----- Write 3
What is the sum of total liabilities?----- Write 4
What is the total Cash Flow from Operating Activitie)?----- Write 5
What is the revenue growth(%)?----- Write 6
What is the net income growth(%)?----- Write 7
What is the assets growth(%)?----- Write 8
What is the liabilities growth(%)?----- Write 9
What is the cash flow from operations growth(%)?----- Write 10
What is the year by year average revenue growth(%)?----- Write 11
What is the year by year average net income growth rate(%)?----- Write 12
What is the year by year average assets growth rate(%)?----- Write 13
What is the year by year average liabilities growth rate(%)?----- Write 14
What is the year by year average cash flow from operations growth rate(%)?----- Write 15
enter your query:
1
The Total Revenue for Microsoft for the year 2021 is $168088
-------------------------------------------------------------------------

Enter Hi to start the chatbot session; type 'exit' to quit):Hi

Hello! Welcome to AI Driven Financial Chatbot!!!

I can help you with your financial queries
Please select the company name from below:

1.Microsoft
2.Tesla
3.Apple
Enter Company Name: Tesla
The data for the fiscal year 2023, 2022, and 2021 is currently available
The fiscal year for the selected company :2022
....FOLLOW THIS INSTRUCTION BEFORE WRITE QUERY....
****************************************************
What is the total revenue?----- Write 1
What is the Net Income?----- Write 2
What is the sum of total assets?----- Write 3
What is the sum of total liabilities?----- Write 4
What is the total Cash Flow from Operating Activitie)?----- Write 5
What is the revenue growth(%)?----- Write 6
What is the net income growth(%)?----- Write 7
What is the assets growth(%)?----- Write 8
What is the liabilities growth(%)?----- Write 9
What is the cash flow from operations growth(%)?----- Write 10
What is the year by year average revenue growth(%)?----- Write 11
What is the year by year average net income growth rate(%)?----- Write 12
What is the year by year average assets growth rate(%)?----- Write 13
What is the year by year average liabilities growth rate(%)?----- Write 14
What is the year by year average cash flow from operations growth rate(%)?----- Write 15
enter your query:
2
The net_income for Tesla for the year 2022 is $12556
-------------------------------------------------------------------------

Enter Hi to start the chatbot session; type 'exit' to quit):Hi

Hello! Welcome to AI Driven Financial Chatbot!!!

I can help you with your financial queries
Please select the company name from below:

1.Microsoft
2.Tesla
3.Apple
Enter Company Name: Apple
The data for the fiscal year 2023, 2022, and 2021 is currently available
The fiscal year for the selected company :2023
....FOLLOW THIS INSTRUCTION BEFORE WRITE QUERY....
****************************************************
What is the total revenue?----- Write 1
What is the Net Income?----- Write 2
What is the sum of total assets?----- Write 3
What is the sum of total liabilities?----- Write 4
What is the total Cash Flow from Operating Activitie)?----- Write 5
What is the revenue growth(%)?----- Write 6
What is the net income growth(%)?----- Write 7
What is the assets growth(%)?----- Write 8
What is the liabilities growth(%)?----- Write 9
What is the cash flow from operations growth(%)?----- Write 10
What is the year by year average revenue growth(%)?----- Write 11
What is the year by year average net income growth rate(%)?----- Write 12
What is the year by year average assets growth rate(%)?----- Write 13
What is the year by year average liabilities growth rate(%)?----- Write 14
What is the year by year average cash flow from operations growth rate(%)?----- Write 15
enter your query:
3
The Total Assets for Apple for the year 2023 is $352583
-------------------------------------------------------------------------

Enter Hi to start the chatbot session; type 'exit' to quit):Hi

Hello! Welcome to AI Driven Financial Chatbot!!!

I can help you with your financial queries
Please select the company name from below:

1.Microsoft
2.Tesla
3.Apple
Enter Company Name: Microsoft
The data for the fiscal year 2023, 2022, and 2021 is currently available
The fiscal year for the selected company :2022
....FOLLOW THIS INSTRUCTION BEFORE WRITE QUERY....
****************************************************
What is the total revenue?----- Write 1
What is the Net Income?----- Write 2
What is the sum of total assets?----- Write 3
What is the sum of total liabilities?----- Write 4
What is the total Cash Flow from Operating Activitie)?----- Write 5
What is the revenue growth(%)?----- Write 6
What is the net income growth(%)?----- Write 7
What is the assets growth(%)?----- Write 8
What is the liabilities growth(%)?----- Write 9
What is the cash flow from operations growth(%)?----- Write 10
What is the year by year average revenue growth(%)?----- Write 11
What is the year by year average net income growth rate(%)?----- Write 12
What is the year by year average assets growth rate(%)?----- Write 13
What is the year by year average liabilities growth rate(%)?----- Write 14
What is the year by year average cash flow from operations growth rate(%)?----- Write 15
enter your query:
4
The Total Liabilities for Microsoft for the year 2022 is $198298
-------------------------------------------------------------------------

Enter Hi to start the chatbot session; type 'exit' to quit):Hi

Hello! Welcome to AI Driven Financial Chatbot!!!

I can help you with your financial queries
Please select the company name from below:

1.Microsoft
2.Tesla
3.Apple
Enter Company Name: Apple
The data for the fiscal year 2023, 2022, and 2021 is currently available
The fiscal year for the selected company :2021
....FOLLOW THIS INSTRUCTION BEFORE WRITE QUERY....
****************************************************
What is the total revenue?----- Write 1
What is the Net Income?----- Write 2
What is the sum of total assets?----- Write 3
What is the sum of total liabilities?----- Write 4
What is the total Cash Flow from Operating Activitie)?----- Write 5
What is the revenue growth(%)?----- Write 6
What is the net income growth(%)?----- Write 7
What is the assets growth(%)?----- Write 8
What is the liabilities growth(%)?----- Write 9
What is the cash flow from operations growth(%)?----- Write 10
What is the year by year average revenue growth(%)?----- Write 11
What is the year by year average net income growth rate(%)?----- Write 12
What is the year by year average assets growth rate(%)?----- Write 13
What is the year by year average liabilities growth rate(%)?----- Write 14
What is the year by year average cash flow from operations growth rate(%)?----- Write 15
enter your query:
5
The Cash Flow from Operations for Apple for the year 2021 is $104038
-------------------------------------------------------------------------

Enter Hi to start the chatbot session; type 'exit' to quit):Hi

Hello! Welcome to AI Driven Financial Chatbot!!!

I can help you with your financial queries
Please select the company name from below:

1.Microsoft
2.Tesla
3.Apple
Enter Company Name: Microsoft
The data for the fiscal year 2023, 2022, and 2021 is currently available
The fiscal year for the selected company :2022
....FOLLOW THIS INSTRUCTION BEFORE WRITE QUERY....
****************************************************
What is the total revenue?----- Write 1
What is the Net Income?----- Write 2
What is the sum of total assets?----- Write 3
What is the sum of total liabilities?----- Write 4
What is the total Cash Flow from Operating Activitie)?----- Write 5
What is the revenue growth(%)?----- Write 6
What is the net income growth(%)?----- Write 7
What is the assets growth(%)?----- Write 8
What is the liabilities growth(%)?----- Write 9
What is the cash flow from operations growth(%)?----- Write 10
What is the year by year average revenue growth(%)?----- Write 11
What is the year by year average net income growth rate(%)?----- Write 12
What is the year by year average assets growth rate(%)?----- Write 13
What is the year by year average liabilities growth rate(%)?----- Write 14
What is the year by year average cash flow from operations growth rate(%)?----- Write 15
enter your query:
6
The Total Revenue Growth for Microsoft for the year 2022 is $-6.4389(%)
-------------------------------------------------------------------------

Enter Hi to start the chatbot session; type 'exit' to quit):Hi

Hello! Welcome to AI Driven Financial Chatbot!!!

I can help you with your financial queries
Please select the company name from below:

1.Microsoft
2.Tesla
3.Apple
Enter Company Name: Tesla
The data for the fiscal year 2023, 2022, and 2021 is currently available
The fiscal year for the selected company :2022
....FOLLOW THIS INSTRUCTION BEFORE WRITE QUERY....
****************************************************
What is the total revenue?----- Write 1
What is the Net Income?----- Write 2
What is the sum of total assets?----- Write 3
What is the sum of total liabilities?----- Write 4
What is the total Cash Flow from Operating Activitie)?----- Write 5
What is the revenue growth(%)?----- Write 6
What is the net income growth(%)?----- Write 7
What is the assets growth(%)?----- Write 8
What is the liabilities growth(%)?----- Write 9
What is the cash flow from operations growth(%)?----- Write 10
What is the year by year average revenue growth(%)?----- Write 11
What is the year by year average net income growth rate(%)?----- Write 12
What is the year by year average assets growth rate(%)?----- Write 13
What is the year by year average liabilities growth rate(%)?----- Write 14
What is the year by year average cash flow from operations growth rate(%)?----- Write 15
enter your query:
7
The Total Net Income Growth for Tesla for the year 2022 is $-16.148(%)
-------------------------------------------------------------------------

Enter Hi to start the chatbot session; type 'exit' to quit):Hi

Hello! Welcome to AI Driven Financial Chatbot!!!

I can help you with your financial queries
Please select the company name from below:

1.Microsoft
2.Tesla
3.Apple
Enter Company Name: Apple
The data for the fiscal year 2023, 2022, and 2021 is currently available
The fiscal year for the selected company :2023
....FOLLOW THIS INSTRUCTION BEFORE WRITE QUERY....
****************************************************
What is the total revenue?----- Write 1
What is the Net Income?----- Write 2
What is the sum of total assets?----- Write 3
What is the sum of total liabilities?----- Write 4
What is the total Cash Flow from Operating Activitie)?----- Write 5
What is the revenue growth(%)?----- Write 6
What is the net income growth(%)?----- Write 7
What is the assets growth(%)?----- Write 8
What is the liabilities growth(%)?----- Write 9
What is the cash flow from operations growth(%)?----- Write 10
What is the year by year average revenue growth(%)?----- Write 11
What is the year by year average net income growth rate(%)?----- Write 12
What is the year by year average assets growth rate(%)?----- Write 13
What is the year by year average liabilities growth rate(%)?----- Write 14
What is the year by year average cash flow from operations growth rate(%)?----- Write 15
enter your query:
8
The Total Assets Growth for Apple for the year 2023 is $0.0(%)
-------------------------------------------------------------------------

Enter Hi to start the chatbot session; type 'exit' to quit):Hi

Hello! Welcome to AI Driven Financial Chatbot!!!

I can help you with your financial queries
Please select the company name from below:

1.Microsoft
2.Tesla
3.Apple
Enter Company Name: Tesla
The data for the fiscal year 2023, 2022, and 2021 is currently available
The fiscal year for the selected company :2023
....FOLLOW THIS INSTRUCTION BEFORE WRITE QUERY....
****************************************************
What is the total revenue?----- Write 1
What is the Net Income?----- Write 2
What is the sum of total assets?----- Write 3
What is the sum of total liabilities?----- Write 4
What is the total Cash Flow from Operating Activitie)?----- Write 5
What is the revenue growth(%)?----- Write 6
What is the net income growth(%)?----- Write 7
What is the assets growth(%)?----- Write 8
What is the liabilities growth(%)?----- Write 9
What is the cash flow from operations growth(%)?----- Write 10
What is the year by year average revenue growth(%)?----- Write 11
What is the year by year average net income growth rate(%)?----- Write 12
What is the year by year average assets growth rate(%)?----- Write 13
What is the year by year average liabilities growth rate(%)?----- Write 14
What is the year by year average cash flow from operations growth rate(%)?----- Write 15
enter your query:
9
The Total Liabilities Growth for Tesla for the year 2023 is $0.0(%)
-------------------------------------------------------------------------

Enter Hi to start the chatbot session; type 'exit' to quit):Hi

Hello! Welcome to AI Driven Financial Chatbot!!!

I can help you with your financial queries
Please select the company name from below:

1.Microsoft
2.Tesla
3.Apple
Enter Company Name: Microsoft
The data for the fiscal year 2023, 2022, and 2021 is currently available
The fiscal year for the selected company :2021
....FOLLOW THIS INSTRUCTION BEFORE WRITE QUERY....
****************************************************
What is the total revenue?----- Write 1
What is the Net Income?----- Write 2
What is the sum of total assets?----- Write 3
What is the sum of total liabilities?----- Write 4
What is the total Cash Flow from Operating Activitie)?----- Write 5
What is the revenue growth(%)?----- Write 6
What is the net income growth(%)?----- Write 7
What is the assets growth(%)?----- Write 8
What is the liabilities growth(%)?----- Write 9
What is the cash flow from operations growth(%)?----- Write 10
What is the year by year average revenue growth(%)?----- Write 11
What is the year by year average net income growth rate(%)?----- Write 12
What is the year by year average assets growth rate(%)?----- Write 13
What is the year by year average liabilities growth rate(%)?----- Write 14
What is the year by year average cash flow from operations growth rate(%)?----- Write 15
enter your query:
10
The Total Cash Flow from Operations Growth for Microsoft for the year 2021 is $-13.8092(%)
-------------------------------------------------------------------------

Enter Hi to start the chatbot session; type 'exit' to quit):Hi

Hello! Welcome to AI Driven Financial Chatbot!!!

I can help you with your financial queries
Please select the company name from below:

1.Microsoft
2.Tesla
3.Apple
Enter Company Name: Tesla
The data for the fiscal year 2023, 2022, and 2021 is currently available
The fiscal year for the selected company :2022
....FOLLOW THIS INSTRUCTION BEFORE WRITE QUERY....
****************************************************
What is the total revenue?----- Write 1
What is the Net Income?----- Write 2
What is the sum of total assets?----- Write 3
What is the sum of total liabilities?----- Write 4
What is the total Cash Flow from Operating Activitie)?----- Write 5
What is the revenue growth(%)?----- Write 6
What is the net income growth(%)?----- Write 7
What is the assets growth(%)?----- Write 8
What is the liabilities growth(%)?----- Write 9
What is the cash flow from operations growth(%)?----- Write 10
What is the year by year average revenue growth(%)?----- Write 11
What is the year by year average net income growth rate(%)?----- Write 12
What is the year by year average assets growth rate(%)?----- Write 13
What is the year by year average liabilities growth rate(%)?----- Write 14
What is the year by year average cash flow from operations growth rate(%)?----- Write 15
enter your query:
11
The Year By Year Average Revenue Growth Rate(%) from 2021 to 2023 for Tesla is $0.0(%)
-------------------------------------------------------------------------

Enter Hi to start the chatbot session; type 'exit' to quit):Hi

Hello! Welcome to AI Driven Financial Chatbot!!!

I can help you with your financial queries
Please select the company name from below:

1.Microsoft
2.Tesla
3.Apple
Enter Company Name: Apple
The data for the fiscal year 2023, 2022, and 2021 is currently available
The fiscal year for the selected company :2022
....FOLLOW THIS INSTRUCTION BEFORE WRITE QUERY....
****************************************************
What is the total revenue?----- Write 1
What is the Net Income?----- Write 2
What is the sum of total assets?----- Write 3
What is the sum of total liabilities?----- Write 4
What is the total Cash Flow from Operating Activitie)?----- Write 5
What is the revenue growth(%)?----- Write 6
What is the net income growth(%)?----- Write 7
What is the assets growth(%)?----- Write 8
What is the liabilities growth(%)?----- Write 9
What is the cash flow from operations growth(%)?----- Write 10
What is the year by year average revenue growth(%)?----- Write 11
What is the year by year average net income growth rate(%)?----- Write 12
What is the year by year average assets growth rate(%)?----- Write 13
What is the year by year average liabilities growth rate(%)?----- Write 14
What is the year by year average cash flow from operations growth rate(%)?----- Write 15
enter your query:
12
The Year By Year Average Net Income Growth Rate(%) from 2021 to 2023 for Apple is $-0.746(%)
-------------------------------------------------------------------------

Enter Hi to start the chatbot session; type 'exit' to quit):Hi

Hello! Welcome to AI Driven Financial Chatbot!!!

I can help you with your financial queries
Please select the company name from below:

1.Microsoft
2.Tesla
3.Apple
Enter Company Name: Microsoft
The data for the fiscal year 2023, 2022, and 2021 is currently available
The fiscal year for the selected company :2021
....FOLLOW THIS INSTRUCTION BEFORE WRITE QUERY....
****************************************************
What is the total revenue?----- Write 1
What is the Net Income?----- Write 2
What is the sum of total assets?----- Write 3
What is the sum of total liabilities?----- Write 4
What is the total Cash Flow from Operating Activitie)?----- Write 5
What is the revenue growth(%)?----- Write 6
What is the net income growth(%)?----- Write 7
What is the assets growth(%)?----- Write 8
What is the liabilities growth(%)?----- Write 9
What is the cash flow from operations growth(%)?----- Write 10
What is the year by year average revenue growth(%)?----- Write 11
What is the year by year average net income growth rate(%)?----- Write 12
What is the year by year average assets growth rate(%)?----- Write 13
What is the year by year average liabilities growth rate(%)?----- Write 14
What is the year by year average cash flow from operations growth rate(%)?----- Write 15
enter your query:
13
The Year By Year Average Assets Growth Rate(%) from 2021 to 2023 for Microsoft is $-6.6517(%)
-------------------------------------------------------------------------

Enter Hi to start the chatbot session; type 'exit' to quit):Hi

Hello! Welcome to AI Driven Financial Chatbot!!!

I can help you with your financial queries
Please select the company name from below:

1.Microsoft
2.Tesla
3.Apple
Enter Company Name: Apple